### ISSUE TITLE
it fails to compile on android

### ISSUE THREAD

**Issue by axeljeremy7** [maxim-kolesnikov/react-native-heic-converter#21]
the promise convert is not recognized as promise and cause issues when trying to build the app, my app runs in both platforms fine but for android I have to manually remove the `await ` and `async` in order to be compiled and built

**Comment by maxim-kolesnikov** [comment]
Hi! What about make use of platform-specific extensions?
https://reactnative.dev/docs/platform-specific-code#platform-specific-extensions
