### ISSUE TITLE
Update node version to the latest tagged version

### ISSUE THREAD

**Issue by ineedthekeyboard** [maxim-kolesnikov/react-native-heic-converter#27]
Node shows the latest built version as 1.3.0.. when you have the latest tagged release at 1.3.1

**Comment by estani** [comment]
and v1.3.0 pin react-native to '^0.42.2'
And for dome reason unknown to me, npm thinks that `0.63.4` is not in `0.42.2` range...

```
npm ERR! While resolving: react-native-heic-converter@1.3.0
npm ERR! Found: react-native@0.63.4
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.63.4" from the root project
npm ERR!   peer react-native@">=0.63.0" from @codler/react-native-keyboard-aware-scroll-view@1.0.1
npm ERR!   node_modules/@codler/react-native-keyboard-aware-scroll-view
npm ERR!     @codler/react-native-keyboard-aware-scroll-view@"1.0.1" from native-base@2.15.2
npm ERR!     node_modules/native-base
npm ERR!       native-base@"^2.13.12" from @comjoo/ui-kit-mobile@1.2.0
npm ERR!       node_modules/@comjoo/ui-kit-mobile
npm ERR!         @comjoo/ui-kit-mobile@"^1.2.0" from the root project
npm ERR!   42 more (@comjoo/easy-core, react-native-image-crop-picker, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.41.2" from react-native-heic-converter@1.3.0
npm ERR! node_modules/react-native-heic-converter
npm ERR!   react-native-heic-converter@"^1.3.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react-native@0.41.2
npm ERR! node_modules/react-native
npm ERR!   peer react-native@"^0.41.2" from react-native-heic-converter@1.3.0
npm ERR!   node_modules/react-native-heic-converter
npm ERR!     react-native-heic-converter@"^1.3.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
```

this page thinks like I do: https://jubianchi.github.io/semver-check/#/^0.41.2/0.63.4

**Comment by maxim-kolesnikov** [comment]
https://github.com/maxim-kolesnikov/react-native-heic-converter/compare

**Comment by tendolukwago** [comment]
> https://github.com/maxim-kolesnikov/react-native-heic-converter/compare

I'm confused by this comment. I believe the problem was that this was never released to NPM.

https://www.npmjs.com/package/react-native-heic-converter

**Comment by Jake-Kuznicki** [comment]
Bumping this, the tag 1.3.1 on the repository was successful but never released on NPM. @maxim-kolesnikov 

<img width="792" alt="image" src="https://user-images.githubusercontent.com/13613581/189249566-6b084f30-0492-44f8-a3be-2e5e92c1d355.png">

**Comment by maxim-kolesnikov** [comment]
Resolved

<img width="795" alt="image" src="https://user-images.githubusercontent.com/10406538/189519960-7b3e925a-db76-47e6-b993-366569c4481e.png">

**Comment by maxim-kolesnikov** [comment]
Please open a new issue if you are still having trouble.
