### ISSUE TITLE
FAILURE [TypeError: null is not an object (evaluating 'RNHeicConverter.convert')]

### ISSUE THREAD

**Issue by Larens94** [maxim-kolesnikov/react-native-heic-converter#37]
hello the library returns this error:
FAILURE [TypeError: null is not an object (evaluating 'RNHeicConverter.convert')]

could you give me support?

**Comment by maxim-kolesnikov** [comment]
All I can say right now is that this module only works on iOS, and installing CocoaPods is a require for it to work: 
https://github.com/maxim-kolesnikov/react-native-heic-converter#manual-installation

It seems like you need to create a more explicit description, not just "I have null, help me"

**Comment by maxim-kolesnikov** [comment]
You can reopen the issue if you are still experiencing difficulties
