### ISSUE TITLE
Please release react-native-windows dependency update

### ISSUE THREAD

**Issue by cwrllab** [maxim-kolesnikov/react-native-heic-converter#46]
This [commit](https://github.com/maxim-kolesnikov/react-native-heic-converter/commit/bc8fc0e40d62088b067d9a7eea25ddc3dcd17fcf) is not included in release `1.3.1`

I could not resolve react native windows because of the npm peer dependency error. 
Please release with this commit.

**Comment by maxim-kolesnikov** [comment]
https://www.npmjs.com/package/react-native-heic-converter/v/1.3.2

**Comment by cwrllab** [comment]
Thanks!
