### ISSUE TITLE
add TypeScript types

### ISSUE THREAD

**Issue by Splicer97** [maxim-kolesnikov/react-native-heic-converter#50]

**Comment by maxim-kolesnikov** [comment]
https://github.com/maxim-kolesnikov/react-native-heic-converter/pulls

**Comment by Splicer97** [comment]
I cant create PR& Recieve this -- Pull request creation failed. Validation failed: must be a collaborator

**Comment by Splicer97** [comment]
Please^ create file index.d.ts and add this code 

`declare module "react-native-heic-converter" {
  interface IHEICConverter {
    convert(params: {
      path: string;
      quality?: number;
      extension?: "jpg" | "png" | "base64";
    }): Promise<{
      success: true;
      path: string;
      error?: string;
      base64?: string;
    }>;
  }
  export default HEICConverter as IHEICConverter;
}
`

**Comment by Splicer97** [comment]
@maxim-kolesnikov
