### ISSUE TITLE
Performance overview?

### ISSUE THREAD

**Issue by awnumar** [maxim-kolesnikov/react-native-heic-converter#6]
Is there any data/benchmarks on the performance of this library on different platforms, or even a rough estimate to its temporal/computational/memory cost?

**Comment by maxim-kolesnikov** [comment]
@awnumar 
Hi!
No, but you can do it. 
react-native-heic-converter  supported only iOS platform.

**Comment by awnumar** [comment]
Alright, thanks for that.
