### ISSUE TITLE
Still under maintenance?

### ISSUE THREAD

**Issue by Psiiirus** [maxim-kolesnikov/react-native-heic-converter#7]
Good morning,
i was wondering if you(@maxim-kolesnikov) going to update this repo to RN60?

Cheers,
Toni

**Comment by maxim-kolesnikov** [comment]
@MM-Psiiirus 
Hi, I will try do it before saturday

**Comment by Psiiirus** [comment]
@maxim-kolesnikov  thanks for merging, are you planning to do a version bump as well today?

**Comment by maxim-kolesnikov** [comment]
@Psiiirus 
Yes, v1.2.1 was published

**Comment by maxim-kolesnikov** [comment]
@Psiiirus resolved
